/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia1carlosreyes;

import javax.swing.JOptionPane;

/**
 *
 * @author ccerr
 */
public class CalcularCum extends javax.swing.JFrame {

    /**
     * Creates new form CalcularCum
     */
    public CalcularCum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbUv2 = new javax.swing.JComboBox<>();
        cbCarreras = new javax.swing.JComboBox<>();
        lbCum = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbMateria5 = new javax.swing.JComboBox<>();
        cbMateria3 = new javax.swing.JComboBox<>();
        cbMateria1 = new javax.swing.JComboBox<>();
        cbMateria4 = new javax.swing.JComboBox<>();
        cbMateria2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbCiclo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbUv1 = new javax.swing.JComboBox<>();
        cbUv4 = new javax.swing.JComboBox<>();
        tfNota1 = new javax.swing.JTextField();
        tfNota3 = new javax.swing.JTextField();
        tfNota4 = new javax.swing.JTextField();
        tfNota5 = new javax.swing.JTextField();
        tFNota2 = new javax.swing.JTextField();
        lbEstado3 = new javax.swing.JLabel();
        lbEstado1 = new javax.swing.JLabel();
        lbEstado4 = new javax.swing.JLabel();
        lbEstado2 = new javax.swing.JLabel();
        lbEstado5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbUv5 = new javax.swing.JComboBox<>();
        cbUv3 = new javax.swing.JComboBox<>();
        lbComentario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Control de Notas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Carrera:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ciclo:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("CUM");

        cbUv2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4" }));

        cbCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Ingenieria en Sistemas", "Ingenieria Electronica", "Ingenieria Industrial", "Ingenieria en Agronegocios", " " }));

        lbCum.setText("0.0");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Materia");

        cbMateria5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione", "Base de Datos II", "Desarrollo de Software I", "Investigacion de Opereaciones", "Legislacion Aplicada a la Empresa", "Electronica" }));
        cbMateria5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria5ActionPerformed(evt);
            }
        });

        cbMateria3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione", "Base de Datos II", "Desarrollo de Software I", "Investigacion de Opereaciones", "Legislacion Aplicada a la Empresa", "Electronica" }));
        cbMateria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria3ActionPerformed(evt);
            }
        });

        cbMateria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione", "Base de Datos II", "Desarrollo de Software I", "Investigacion de Opereaciones", "Legislacion Aplicada a la Empresa", "Electronica" }));
        cbMateria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria1ActionPerformed(evt);
            }
        });

        cbMateria4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione", "Base de Datos II", "Desarrollo de Software I", "Investigacion de Opereaciones", "Legislacion Aplicada a la Empresa", "Electronica" }));
        cbMateria4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria4ActionPerformed(evt);
            }
        });

        cbMateria2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione", "Base de Datos II", "Desarrollo de Software I", "Investigacion de Opereaciones", "Legislacion Aplicada a la Empresa", "Electronica" }));
        cbMateria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Nota");

        cbCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Ciclo 01", "Ciclo 02" }));
        cbCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCicloActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("UV");

        cbUv1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4" }));
        cbUv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUv1ActionPerformed(evt);
            }
        });

        cbUv4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4" }));
        cbUv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUv4ActionPerformed(evt);
            }
        });

        tfNota1.setEditable(false);

        tfNota3.setEditable(false);
        tfNota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNota3ActionPerformed(evt);
            }
        });

        tfNota4.setEditable(false);

        tfNota5.setEditable(false);

        tFNota2.setEditable(false);

        lbEstado3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbEstado3.setText("Estado");

        lbEstado1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbEstado1.setText("Estado");

        lbEstado4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbEstado4.setText("Estado");

        lbEstado2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbEstado2.setText("Estado");

        lbEstado5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbEstado5.setText("Estado");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbUv5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4" }));
        cbUv5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUv5ActionPerformed(evt);
            }
        });

        cbUv3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4" }));
        cbUv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUv3ActionPerformed(evt);
            }
        });

        lbComentario.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUv4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUv5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfNota5, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(tfNota4)
                                    .addComponent(tfNota3)
                                    .addComponent(tFNota2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNota1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEstado2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel4)
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCum, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUv1)
                    .addComponent(tfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstado1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstado2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstado3)
                    .addComponent(cbUv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstado4)
                    .addComponent(cbUv4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado5)
                            .addComponent(cbUv5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(28, 28, 28)
                .addComponent(lbComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMateria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria3ActionPerformed

    private void cbMateria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria1ActionPerformed

    private void cbMateria4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria4ActionPerformed

    private void cbMateria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria2ActionPerformed

    private void cbMateria5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria5ActionPerformed

    private void tfNota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNota3ActionPerformed

    private void cbUv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUv1ActionPerformed

    private void cbUv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUv3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUv3ActionPerformed

    private void cbUv4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUv4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUv4ActionPerformed

    private void cbUv5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUv5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUv5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String CicloActual = "";
        String Carrea = "";
        
        String SelectCarrera = (String)this.cbCarreras.getSelectedItem();
        String cicloSeleccionado = (String)this.cbCiclo.getSelectedItem();
        
        //Validacion de los campos
        if("Seleccione".equals(SelectCarrera))
        {
            JOptionPane.showMessageDialog(this,"Selecciones una Carrera","Eror",JOptionPane.ERROR_MESSAGE);
            return;
        }
        //validando el nombre
        if(tfNombre.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Ingrese un valor en el campo Nomobre","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Validacion de Ciclo
        if(!"Ciclo 01".equals(cicloSeleccionado) && !"Ciclo 02".equals(cicloSeleccionado))
        {
            JOptionPane.showMessageDialog(this,"Sleccione un ciclo valido","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Obtener la seleecion de nombre de las materias
        String Materia1 = (String) this.cbMateria1.getSelectedItem();
        String Materia2 = (String) this.cbMateria2.getSelectedItem();
        String Materia3 = (String) this.cbMateria3.getSelectedItem(); 
        String Materia4 = (String) this.cbMateria4.getSelectedItem();
        String Materia5 = (String) this.cbMateria5.getSelectedItem();
        
        //Verificar que todos los JCcombobox de nombre y materia esten seleccionados
        if("-Selecciones".equals(Materia1) || "-Selecciones".equals(Materia2)){
            JOptionPane.showMessageDialog(this, "Seleccione una materia del ciclo");
        }
        //Calcular CUM
        String nota1 = tfNota1.getText();
        String nota2 = tFNota2.getText();
        String nota3 = tfNota3.getText();
        String nota4 = tfNota4.getText();
        String nota5 = tfNota5.getText();
        
        if(nota1.isEmpty() || nota2.isEmpty() || nota3.isEmpty()|| nota4.isEmpty() || nota5.isEmpty()){
        JOptionPane.showMessageDialog(this, "Ingrese todas las notas de las materia correspondientes");
        return;
        }
        
        double notaMateria1 = Double.parseDouble(nota1);
        double notaMateria2 = Double.parseDouble(nota2);
        double notaMateria3 = Double.parseDouble(nota3);
        double notaMateria4 = Double.parseDouble(nota4);
        double notaMateria5 = Double.parseDouble(nota5);
        
        //Proceso ooperacion con las notas
        
        int uvMateria1 = Integer.parseInt((String) this.cbUv1.getSelectedItem());
        int uvMateria2 = Integer.parseInt((String) this.cbUv2.getSelectedItem());        
        int uvMateria3 = Integer.parseInt((String) this.cbUv3.getSelectedItem());
        int uvMateria4 = Integer.parseInt((String) this.cbUv4.getSelectedItem());
        int uvMateria5 = Integer.parseInt((String) this.cbUv5.getSelectedItem());
        
        double calculador = (notaMateria1 * uvMateria1 )+
                     (notaMateria2 * uvMateria2 )+
                     (notaMateria3 * uvMateria3 )+
                     (notaMateria4 * uvMateria4 )+
                     (notaMateria5 * uvMateria5 );
        
       int denominador = uvMateria1 + uvMateria2 + uvMateria3 + uvMateria4 + uvMateria5;
       double CUM = calculador/denominador;
       
       // calcula el CUM
       int aprobadas = 0;
       int reprobadas = 0;
       
       if(notaMateria1 >= 6){
           aprobadas ++;
       }else{
           reprobadas ++;
       }if(notaMateria2 >= 6){
           aprobadas ++;
       }else{
           reprobadas ++;
       }if(notaMateria3 >= 6){
           aprobadas ++;
       }else{
           reprobadas ++;
       }if(notaMateria4 >= 6){
           aprobadas ++;
       }else{
           reprobadas ++;
       }if(notaMateria5 >= 6){
           aprobadas ++;
       }else{
           reprobadas ++;
       }
       
       String formaCUM = String.format(".%2f",CUM);
       
       String estadoMateria1 = notaMateria1 >=6? "Aprobada" : "Reprobado";
        String estadoMateria2 = notaMateria1 >=6? "Aprobada" : "Reprobado";
         String estadoMateria3 = notaMateria1 >=6? "Aprobada" : "Reprobado";
          String estadoMateria4 = notaMateria1 >=6? "Aprobada" : "Reprobado";
           String estadoMateria5 = notaMateria1 >=6? "Aprobada" : "Reprobado";
           
           // MOstrar si las materias estan aprobadas
           
           this.lbEstado1.setText(estadoMateria1);
           this.lbEstado2.setText(estadoMateria2);
           this.lbEstado3.setText(estadoMateria3);
           this.lbEstado4.setText(estadoMateria4);
           this.lbEstado5.setText(estadoMateria5);
           
           String nombre = this.tfNombre.getText();
           lbCum.setText(String.format(".2f",CUM));
           this.lbComentario.setText(" "+nombre+"  Carrera "+SelectCarrera+ "Estado actual es"+ aprobadas+" materias aprobadas y "
                                     + reprobadas + " reprobadas "+ "su CUM es"+ CUM);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCicloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcularCum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcularCum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcularCum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcularCum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcularCum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCarreras;
    private javax.swing.JComboBox<String> cbCiclo;
    private javax.swing.JComboBox<String> cbMateria1;
    private javax.swing.JComboBox<String> cbMateria2;
    private javax.swing.JComboBox<String> cbMateria3;
    private javax.swing.JComboBox<String> cbMateria4;
    private javax.swing.JComboBox<String> cbMateria5;
    private javax.swing.JComboBox<String> cbUv1;
    private javax.swing.JComboBox<String> cbUv2;
    private javax.swing.JComboBox<String> cbUv3;
    private javax.swing.JComboBox<String> cbUv4;
    private javax.swing.JComboBox<String> cbUv5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbComentario;
    private javax.swing.JLabel lbCum;
    private javax.swing.JLabel lbEstado1;
    private javax.swing.JLabel lbEstado2;
    private javax.swing.JLabel lbEstado3;
    private javax.swing.JLabel lbEstado4;
    private javax.swing.JLabel lbEstado5;
    private javax.swing.JTextField tFNota2;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNota1;
    private javax.swing.JTextField tfNota3;
    private javax.swing.JTextField tfNota4;
    private javax.swing.JTextField tfNota5;
    // End of variables declaration//GEN-END:variables
}
